image: europeanxfel/karabo-ci:miniconda-3

before_script:
    - source ci/prepare.sh

stages:
    - unittest

unittest:
    stage: unittest

    script:
        - source ci/build.sh
        - source ci/test.sh
