dist: xenial
sudo: required
language: cpp

services:
  - xvfb

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=gcc GCC=6
    - os: linux
      if: branch = master
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=gcc GCC=7

env:
  global:
    - DISPLAY=":99.0"
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$COMPILER" == "gcc" ]]; then
        export CXX=g++-$GCC CC=gcc-$GCC;
      fi
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      MINCONDA_OS=$MINCONDA_LINUX;
    fi
  - wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install -y cmake -c conda-forge
  - which python
  - python --version
  - which pip
  - pip --version
  # QT_DEBUG_PLUGINS
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt install -y libxkbcommon-x11-0;
      pip install -e .[test];
    fi

before_script:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1400x900x24
  - sleep 3

script:
  # test parallel version
  - python setup.py build_ext --with-tests
  - python setup.py test -v

  # test series version
  - export FOAM_WITH_TBB=0
  - export FOAM_WITH_XSIMD=0
  - export XTENSOR_WITH_TBB=0
  - export XTENSOR_WITH_XSIMD=0
  - python setup.py build_ext --with-tests
  - python setup.py test -v