name: extra_foam

channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - gxx_linux-64>=8
  - libstdcxx-ng
  - cmake>=3.17
  - tbb-devel>=2021
  - tbb>=2021
  - xtensor==0.23.10
  - xtensor-python==0.25.3
  - xtensor-blas==0.19.1
  - xsimd==7.6.0
