name: extra_foam

channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - gxx_linux-64>=8
  - libstdcxx-ng
  - cmake>=3.17
  - tbb-devel>=2021
  - tbb>=2021
  - xtensor==0.24.0
  - xtensor-python==0.26.0
  - xtensor-blas==0.20.0
  - xsimd==8.0.5
  - python>=3.10
