SOURCE:
    # Default source type: FILES or BRIDGE
    DEFAULT_TYPE: 1
    CATEGORY:
        AGIPD:
            PIPELINE:
                MID_DET_AGIPD1M-1/CAL/APPEND_CORRECTED:
                    - image.data
                MID_DET_AGIPD1M-1/DET/*CH0:xtdf:
                    - image.data
        ePix100:
            PIPELINE:
                # the property name for the raw data is 'data.image.data'
                MID_EXP_EPIX-1/DET/RECEIVER:output:
                    - data.image
                MID_EXP_EPIX-2/DET/RECEIVER:output:
                    - data.image
                MID_EXP_EPIX-1/DET/RECEIVER:daqOutput:
                    - data.image.pixels
                MID_EXP_EPIX-2/DET/RECEIVER:daqOutput:
                    - data.image.pixels

DETECTOR:
    AGIPD:
        # AGIPD uses the CFEL geometry format
        GEOMETRY_FILE: agipd_mar18_v11.geom
        BRIDGE_ADDR: 10.253.0.51
        BRIDGE_PORT:  45012
        LOCAL_ADDR: 127.0.0.1
        LOCAL_PORT: 45450
        SAMPLE_DISTANCE: 5.5
        PHOTON_ENERGY: 9.3
