SOURCE:
    # Default source type: FILES or BRIDGE
    DEFAULT_TYPE: 1
    CATEGORY:
        AGIPD:
            PIPELINE:
                SPB_DET_AGIPD1M-1/CAL/APPEND_CORRECTED:
                    - image.data
                SPB_DET_AGIPD1M-1/DET/*CH0:xtdf:
                    - image.data

        JungFrau:
            PIPELINE:
                SPB_IRDA_JF4M/DET/JNGFR0*:daqOutput:
                    - data.adc
                SPB_IRDA_JF4M/DET/JNGFR01:daqOutput:
                    - data.adc
                SPB_IRDA_JF4M/DET/JNGFR02:daqOutput:
                    - data.adc
                SPB_IRDA_JF4M/DET/JNGFR03:daqOutput:
                    - data.adc
                SPB_IRDA_JF4M/DET/JNGFR04:daqOutput:
                    - data.adc
                SPB_IRDA_JF4M/DET/JNGFR05:daqOutput:
                    - data.adc
                SPB_IRDA_JF4M/DET/JNGFR06:daqOutput:
                    - data.adc
                SPB_IRDA_JF4M/DET/JNGFR07:daqOutput:
                    - data.adc
                SPB_IRDA_JF4M/DET/JNGFR08:daqOutput:
                    - data.adc
                SPB_IRDA_JNGFR/DET/MODULE_*:daqOutput:
                    - data.adc

DETECTOR:
    AGIPD:
        # AGIPD uses the CFEL geometry format
        GEOMETRY_FILE: agipd_mar18_v11.geom
        BRIDGE_ADDR: 10.253.0.51
        BRIDGE_PORT: 45012
        LOCAL_ADDR: 127.0.0.1
        LOCAL_PORT: 45450
        SAMPLE_DISTANCE: 5.5
        PHOTON_ENERGY: 9.3
